site_name: Sensei
site_description: The Python framework that provides a quick way to build robust HTTP requests and best API clients. Use type hints, to build requests, with little or no implementation.
site_url: https://sensei.crocofactory.dev
use_directory_urls: false


theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

extra:
  analytics:
    provider: google
    property: G-BBNVDQKG5R
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CrocoFactory/sensei
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/CrocoFactory
    - icon: fontawesome/solid/globe
      link: https://crocofactory.dev

repo_name: CrocoFactory/sensei
repo_url: https://github.com/CrocoFactory/sensei

nav:
  - Sensei: index.md
  - Learn:
    - learn/index.md
    - Type Hints: learn/type_hints.md
    - Concurrency/Parallelism: learn/concurrency_parallelism.md
    - HTTP Requests: learn/http_requests.md
    - User Guide:
      - Motivation: learn/user_guide/motivation.md
      - First Steps: learn/user_guide/first_steps.md
      - Params/Response: learn/user_guide/params_response.md
      - Making Aliases: learn/user_guide/making_aliases.md
      - Preparers/Finalizers: learn/user_guide/preparers_finalizers.md
      - Routed Model: learn/user_guide/routed_model.md
      - Managing Requests: learn/user_guide/managing_requests.md
  - Reference:
      - reference/index.md
      - reference/api_model.md
      - reference/case_converters.md
      - reference/manager.md
      - reference/parameters.md
      - reference/rate_limit.md
      - reference/routed_function.md
      - reference/router.md
  - Sensei People: people.md

plugins:
  social:
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_root_heading: true
          show_if_no_docstring: true
          preload_modules:
            - httpx
          inherited_members: true
          members_order: source
          separate_signature: true
          filters:
            - '!^_'
          docstring_section_style: spacy
          merge_init_into_class: true
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  admonition:
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  pymdownx.betterem:
    smart_enable: all
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:

  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  pymdownx.tabbed:
    alternate_style: true

  pymdownx.details:
  pymdownx.blocks.admonition:
    types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      - info
      - check
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True

  mdx_include:
  markdown_include_variants:

extra_css:
  - css/style.css

extra_javascript:
  - js/script.js
