site_name: Sensei
site_description: The Python framework, providing a quick way to build API wrappers. Use type annotations to build requests with little or no implementation.
site_url: https://sensei.factorycroco.com
use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

repo_name: CrocoFactory/sensei
repo_url: https://github.com/CrocoFactory/sensei

nav:
- Sensei: index.md
